### ISSUE TITLE
share Cristin Merritt talk

### ISSUE THREAD

**Issue by NickleDave** [USRSE/dei-wg#11]
- [x] @nicole-brewer provides video to @JeffCarver (may need to edit first?) to post to YouTube
- [ ] @NickleDave will tweet from US-RSE once it's on YouTube

[edit: @mrmundt is not the one w/the video]

**Comment by JeffCarver** [comment]
If this is a US-RSE Video that needs to be posted on our YouTube Channel, then yes I will need access to the recording so I can process it and upload it.

**Comment by mrmundt** [comment]
I believe @nicole-brewer has the video - she was the Zoom meeting owner.

**Comment by NickleDave** [comment]
Ah got it, thank you @mrmundt

**Comment by NickleDave** [comment]
Talk is now on YouTube

**Comment by NickleDave** [comment]
Closing
