### ISSUE TITLE
Speaker Series - Cristin Merritt - 2022-03-11

### ISSUE THREAD

**Issue by lparsons** [USRSE/dei-wg#15]
* [ ] Share Merritt talk on YouTube, post on channels, add to [newsletter GitHub issue](https://github.com/USRSE/dei-wg/issues/11)

* Cristin Merritt presented on 3/11/2022
* [Event Planning Checklist](https://docs.google.com/spreadsheets/d/173dikpo9-D99vhbyGnj0oXkvOFfVMf8qpgV7Z9FhR9M/edit?usp=sharing)

**Comment by NickleDave** [comment]
Closing this as completed
