### ISSUE TITLE
DEI Media Club 2022: - Jan - Mar

### ISSUE THREAD

**Issue by sk8forether** [USRSE/dei-wg#6]
David Nicholson Leading
Short (~15 min) videos

**Comment by NickleDave** [comment]
My plan is to 
- [ ] have a poll for times after the next meeting
- [ ] go with that time through May

**Comment by lparsons** [comment]
Suggestion from Vanessa:

* [Most Likely to Succeed](https://www.amazon.com/gp/video/detail/B07ZJWB5TG/ref=atv_dp_share_cu_r). It’s on Amazon Prime so I’m not sure if that means not everybody can see it but maybe we could find a way.

**Comment by NickleDave** [comment]
Thank you @lparsons -- meant to make note of that from the email here

**Comment by NickleDave** [comment]
Closing this now that we have decided to make Media Club part of regular DEI-WG meeting schedule
